import assert from 'node:assert/strict';
import {createLighting} from '../server/lighting.mjs';
const calls=[];
const light=createLighting({enabled:true,run:(file,args,options,cb)=>calls.push({args,cb})});
light.set('red');light.set('red');assert.equal(calls.length,1);
assert.equal(calls[0].args[calls[0].args.indexOf('-ExecutionPolicy')+1],'Bypass');
light.set('green');light.set('off');assert.equal(calls.length,1);
calls[0].cb(null,'confirmed red','');assert.equal(calls.length,2);
assert.equal(calls[1].args[calls[1].args.indexOf('-Effect')+1],'off');
calls[1].cb(null,'confirmed off','');light.set('off');assert.equal(calls.length,2);
light.set('bad');assert.equal(calls.length,2);
light.set('green');calls[2].cb(new Error('disconnected'),'','');
light.set('green');assert.equal(calls.length,3);
light.set('off');assert.equal(light.status().confirmed,'off');
light.set('blue');assert.equal(calls.length,4);
assert.equal(calls[3].args[calls[3].args.indexOf('-Effect')+1],'blue');
calls[3].cb(null,'confirmed blue','');light.set('blue');assert.equal(calls.length,4);
light.set('green');assert.equal(calls[4].args.at(-1),'200');calls[4].cb(null,'confirmed green','');
light.set('blue');assert.equal(calls[5].args.at(-1),'900');calls[5].cb(null,'confirmed blue','');
console.log('PASS: deduplication, single-flight, latest request, invalid effect, no failure loop');
